AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring API - com.bountychamp.userservice::bounty-champ-user-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  BountyChampUserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.bountychamp.userservice.StreamLambdaHandler::handleRequest
      Runtime: java8
#      CodeUri: s3://jefftestbucket122333/12358740f0223516c21b595e40875cca
      CodeUri: target/bounty-champ-user-service-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "UserId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "UserId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

Outputs:
  PingApi:
    Description: URL for Ping API
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: PingApi
