package com.bountychamp.service.dynamodb.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

import static com.bountychamp.service.dynamodb.DDBConstants.BOUNTY_TABLE_NAME;

@Getter
@Setter
@DynamoDBTable(tableName = BOUNTY_TABLE_NAME)
public class BountyItem {

    @DynamoDBHashKey(attributeName = "BountyId")
    @DynamoDBAutoGeneratedKey
    private UUID bountyId;

    @DynamoDBAttribute(attributeName="CreatorId")
    private String creatorId;

    @DynamoDBAttribute(attributeName="TargetId")
    private String targetId;

    @DynamoDBAttribute(attributeName="Category")
    private String category;

    @DynamoDBAttribute(attributeName="Description")
    private String description;

    @DynamoDBAttribute(attributeName="AmountInCents")
    private Integer amountInCents;

    @DynamoDBAttribute(attributeName="BountyStatus")
    @DynamoDBTypeConvertedEnum
    private BountyStatus bountyStatus;

    public enum BountyStatus {
        IN_PROGRESS, INCOMPLETE, COMPLETE_PENDING, COMPLETE_PAID, COMPLETE_UNPAID
    }
}