package com.bountychamp.service.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

import static com.bountychamp.service.dynamodb.DDBConstants.BOUNTY_TABLE_NAME;

@Getter
@Setter
@DynamoDBTable(tableName = BOUNTY_TABLE_NAME)
public class BountyItem {

    @DynamoDBHashKey(attributeName = "BountyId")
    @DynamoDBAutoGeneratedKey
    private UUID bountyId;

    @DynamoDBAttribute(attributeName="CreatorId")
    private String creatorId;

    @DynamoDBAttribute(attributeName="TargetId")
    private String targetId;

    @DynamoDBAttribute(attributeName="Category")
    private String category;

    @DynamoDBAttribute(attributeName="Description")
    private String description;

    @DynamoDBAttribute(attributeName="AmountInCents")
    private Integer amountInCents;
}